# Generated by Django 3.1.3 on 2021-06-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
