# Generated by Django 3.1.3 on 2021-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_no',
            field=models.CharField(default='--', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='id_code',
            field=models.CharField(default='--', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_no',
            field=models.CharField(default='--', max_length=255),
        ),
    ]
