# Generated by Django 3.1.3 on 2021-06-18 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210618_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
