# Generated by Django 3.1.3 on 2021-06-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
