# Generated by Django 3.1.3 on 2021-07-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
