# Generated by Django 3.1.3 on 2021-07-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_billingaddress_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='star',
            field=models.IntegerField(default=5),
        ),
    ]
