# Generated by Django 3.1.3 on 2021-07-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_item_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='star',
            field=models.FloatField(default=5),
        ),
    ]
