# Generated by Django 3.1.3 on 2021-07-10 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210709_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
    ]
