# Generated by Django 3.1.3 on 2021-07-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210715_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description_short',
            field=models.TextField(),
        ),
    ]
