# Generated by Django 3.1.3 on 2021-07-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210718_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
