# Generated by Django 3.1.3 on 2021-07-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
            preserve_default=False,
        ),
    ]
