# Generated by Django 3.1.3 on 2021-07-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_item_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
    ]
