# Generated by Django 3.1.3 on 2021-07-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20210728_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='shop.SubCategory'),
        ),
    ]
