# Generated by Django 3.1.3 on 2021-07-30 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20210729_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='color',
            new_name='subcategory',
        ),
    ]
