# Generated by Django 3.1.3 on 2021-07-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20210729_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='image_list',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Images'),
        ),
    ]
